//
//  DataPackageKeys.swift
//  HomiumForIOS
//
//  Created by Eric Münch on 29.05.20.
//  Copyright © 2020 Eric Münch. All rights reserved.
//

import Foundation

//let DATATRANSFER_KEY_INGREDIENTEDIT_ID = "INGREDIENTEDIT:ID" --> DEPRECATED and not longer in code
let DATATRANSFER_KEY_INGREDIENTEDIT_INDEX = "INGREDIENTEDIT:INDEX"
let DATATRANSFER_KEY_INGREDIENTEDIT_TITLE = "INGREDIENTEDIT:TITLE"
let DATATRANSFER_KEY_INGREDIENTEDIT_QUANTITY="INGREDIENTEDIT:QUANTITY"
let DATATRANSFER_KEY_INGREDIENTEDIT_UNIT="INGREDIENTEDIT:UNIT"
let DATATRANSFER_KEY_INGREDIENTEDIT_SHOULD_BE_DELETED = "INGREDIENTEDIT:SHOULDBEDELETED"
