//
//  NotificationNames.swift
//  HomiumForIOS
//
//  Created by Eric Münch on 08.05.20.
//  Copyright © 2020 Eric Münch. All rights reserved.
//

import Foundation

let NOTIFICATION_SETTING_INVENTORY_SORT_CHANGED = "NOTIFICATION_SETTING_INVENTORY_SORT_CHANGED"
let NOTIFICATION_INVENTORY_ITEMS_IMPORTED_FROM_SHOPPINGLIST = "NOTIFICATION_INVENTORY_ITEMS_IMPORTED_FROM_SHOPPINGLIST"
