//
//  UserDefaultsKeys.swift
//  HomiumForIOS
//
//  Created by Eric Münch on 01.04.20.
//  Copyright © 2020 Eric Münch. All rights reserved.
//

import Foundation

//Domain Keys
public let USER_DEFAULTS_DOMAIN_INTERNAL_SETTING = "HOMIUM_USER_DEFAULTS_DOMAIN_INTERNAL_SETTING"
public let USER_DEFAULTS_DOMAIN_USER_SETTING = "HOMIUM_USER_DEFAULTS_DOMAIN_USER_SETTING"

//Internal Settings Keys
public let INTERNAL_SETTING_APP_IS_INITIALIZED = "INTERNAL_SETTING_APP_INITIALIZED"

//User Settings Keys
public let USER_SETTING_SHOPPING_DELETE_QUESTION_ALLOWED = "USER_SETTING_SHOPPING_DELETE_QUESTION_ALLOWED"

public let USER_SETTING_INVENTORY_DELETE_QUESTION_ALLOWED = "USER_SETTING_INVENTORY_DELETE_QUESTION_ALLOWED"

public let USER_SETTING_INVENTORY_SORT_ALGORITHM_ID = "USER_SETTING_INVENTORY_SORT_ALGORITHM_ID"
public let USER_SETTING_RECIPE_DELETE_QUESTION_ALLOWED = "USER_SETTING_RECIPE_DELETE_QUESTION_ALLOWED"

public let USER_SETTING_INVENTORY_IMPORT_OPTIONS = "USER_SETTING_INVENTORY_IMPORT_OPTIONS"
public let USER_SETTING_INVENTORY_AUTO_LOCATION_INTEGRATION = "USER_SETTING_INVENTORY_AUTO_LOCATION_INTEGRATION"
